services:
  web:
    container_name: devevent_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-3010}:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
